I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 264, in script
    python:
  File "renpy/common/00start.rpy", line 268, in <module>
    renpy.call_in_new_context("_main_menu")
KeyError: u'_main_menu_screen'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 264, in script
    python:
  File "C:\renpy-7.2.2-sdk\renpy\ast.py", line 900, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\renpy-7.2.2-sdk\renpy\python.py", line 1930, in py_exec_bytecode
    exec bytecode in globals, locals
  File "renpy/common/00start.rpy", line 268, in <module>
    renpy.call_in_new_context("_main_menu")
  File "C:\renpy-7.2.2-sdk\renpy\game.py", line 332, in call_in_new_context
    return renpy.execution.run_context(False)
  File "C:\renpy-7.2.2-sdk\renpy\execution.py", line 917, in run_context
    context.pop_all_dynamic()
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
    python hide:
  File "C:\renpy-7.2.2-sdk\renpy\execution.py", line 372, in pop_dynamic
    del store[k]
KeyError: u'_main_menu_screen'

Windows-8-6.2.9200
Ren'Py 7.2.2.491
버드나무 꽃 만개할 그날까지 1.1
Sat Jun 22 18:41:41 2019
