I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 49, in script
    python:
  File "game/script.rpy", line 66, in <module>
    config.periodic_callback=check2(image="seng_nom")
  File "game/script.rpy", line 63, in check2
    renpy.hide(image)
Exception: Hide may not run while in init phase.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 49, in script
    python:
  File "F:\renpy\renpy-6.99.13-sdk\renpy\ast.py", line 848, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "F:\renpy\renpy-6.99.13-sdk\renpy\python.py", line 1812, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/script.rpy", line 66, in <module>
    config.periodic_callback=check2(image="seng_nom")
  File "game/script.rpy", line 63, in check2
    renpy.hide(image)
  File "F:\renpy\renpy-6.99.13-sdk\renpy\exports.py", line 702, in hide
    raise Exception("Hide may not run while in init phase.")
Exception: Hide may not run while in init phase.

Windows-8-6.2.9200
Ren'Py 6.99.14.1.3218
버드나무 꽃 만개할 그날까지 1.0
Mon May 21 23:15:38 2018
